/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/DisplayPanel copy.vue')['default']
    Demo: typeof import('./src/components/demo.vue')['default']
    DisplayPanel: typeof import('./src/components/DisplayPanel.vue')['default']
    EditorField: typeof import('./src/components/EditorField.vue')['default']
    EditorPanel: typeof import('./src/components/EditorPanel.vue')['default']
    EditorTag: typeof import('./src/components/EditorTag.vue')['default']
  }
}
